#!/usr/bin/env bash
# vim: ft=sh tw=80

declare help="
Orchestrator script for Alpine's development images.

Usage:
  orchestrator build
  orchestrator --version
  orchestrator -h | --help
"

declare version="
Version: 1.0.0.
Licensed under the MIT terms.
"

declare ARCH
ARCH="$(uname -m)"

run_tests() {
  echo "Tests running for $ARCH:"
  declare test_files="${TESTS_FILES:-tests/$ARCH-*.bats}"
  # shellcheck disable=SC2086
  bats $test_files
}

version() {
  echo "$version"
}

help() {
  echo "$help"
}

main() {
  set -eo pipefail; [[ "$TRACE" ]] && set -x
  declare cmd="$1"
  case "$cmd" in
    test)           shift; run_tests "$@";;
    build)          shift; build "$@";;
    -h|--help)      shift; help "$@";;
    --version)      shift; version;;
    *)              help "$@";;
  esac
}

main "$@"
