#!/usr/bin/env bash
# vim: ft=sh tw=80

declare help="
Orchestrator script for Alpine's development images.

Usage:
  orchestrator test
  orchestrator build
  orchestrator update-base
  orchestrator --version
  orchestrator -h | --help

Options:
  -h --help                 Show this screen.
  --version                 Show versions.
"

declare version="
Version: 1.0.0.
Licensed under the MIT terms.
"

declare ARCH
ARCH="$(uname -m)"

build() {
  docker build -t resnullius/alpine-devel ./versions/3.3/
}

run_tests() {
  echo "Tests running for $ARCH:"
  declare test_files="${TESTS_FILES:-tests/$ARCH-*.bats}"
  # shellcheck disable=SC2086
  bats $test_files
}

update_base() {
  bash bin/update-base.bash run
}

version() {
  echo "$version"
}

help() {
  echo "$help"
}

main() {
  set -eo pipefail; [[ "$TRACE" ]] && set -x
  declare cmd="$1"
  case "$cmd" in
    test)                 shift; run_tests "$@";;
    build)                shift; build "$@";;
    -h|--help)            shift; help "$@";;
    --version)            shift; version;;
    update-base)          shift; update_base;;
    *)                    help "$@";;
  esac
}

main "$@"
