FROM resnullius/alpine:
MAINTAINER Jose-Luis Rivas <me@ghostbar.co>

VOLUME /opt/repo
VOLUME /opt/keys
VOLUME /opt/conf
VOLUME /opt/src

WORKDIR /opt/src

RUN apk-install alpine-sdk && \
  rm /etc/abuild.conf && \
  mkdir -p /var/cache/distfiles && \
  chmod a+w /var/cache/distfiles && \
  adduser -S builder && \
  echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

COPY scripts/* /bin/

USER builder

ENTRYPOINT ["entrypoint.sh"]
